### ISSUE TITLE
ListContainerStats returns empty stats

### ISSUE THREAD

**Issue by middlestone** [brancz/kube-pod-exporter#2]
@brancz I am trying your code, and has a problem to get the stats of the containers, I don't know how to figure out what is wrong, and hope you can help me, thanks beforehand.

I add some log to show what happen, it can list all of the containers, but it can not get their stats.

ts=2019-10-25T11:23:10.35376687Z caller=collector.go:85 component=collector msg="Collect: length of containers is 39"
ts=2019-10-25T11:23:10.504692323Z caller=collector.go:93 component=collector msg="listContainerStatsResponse: &ListContainerStatsResponse{Stats:[],}"

I am using containerd, which should have implemented these two interfaces. correct?
# containerd --version
containerd github.com/containerd/containerd v1.3.0-45-g9c86b8f 9c86b8f5ed49c63b887fe94c369c3a797e79c91f

the command run kube-pod-exporter is just as below.
kube-pod-exporter --listen-address=:8080 --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock

**Comment by brancz** [comment]
> which should have implemented these two interfaces. correct?

Judging by [this](https://github.com/containerd/cri/blob/master/pkg/server/container_stats_list_unix.go), yes.

That said, this was entirely an experiment, and I have no idea what's happening in your case. If you get it to work, and want to contribute something, great! But I don't actively maintain this, so you'll have to figure this out yourself.

**Comment by middlestone** [comment]
thanks brancz, I will try to figure it out first
